name: Debug Example

on: push

jobs:
  debug-job:
    runs-on: ubuntu-latest

    steps:
    - name: Debug secret
      run: echo "::debug::Secret value is $TEST_SECRET12"
      env:
        TEST_SECRET12: ${{ secrets.TEST_SECRET }} 

# REQUIRES ACTIONS_STEP_DEBUG=true secret